import './game-demo.css';
import './progression-overlay';
import { ArmyRoster, BattleSimulator, Economy, MarchManager, Pathfinder, TerrainType, TrainingQueue, UNITS, WorldMap, type UnitCode } from './core';

type View='city'|'map'|'hero'|'army'|'research'|'alliance';
const app=document.querySelector<HTMLDivElement>('#app')!;
const eco=new Economy({WOOD:12500,FOOD:8700,STONE:6200,GOLD:4100,GEMS:210});
const army=new ArmyRoster();army.add('SWORDSMAN',320);army.add('ARCHER',210);army.add('KNIGHT',80);army.add('MAGE',35);
const map=new WorldMap(20,12);for(let x=0;x<20;x++){map.setTerrain(map.ref(x,0),TerrainType.Mountain);map.setTerrain(map.ref(x,11),TerrainType.Water)}for(let y=2;y<9;y++)map.setTerrain(map.ref(9,y),y===5?TerrainType.Plains:TerrainType.Forest);for(let x=12;x<18;x++)map.setTerrain(map.ref(x,8),TerrainType.Desert);map.setTerrain(map.ref(7,4),TerrainType.Ruins);map.setTerrain(map.ref(13,8),TerrainType.Ruins);
const pathfinder=new Pathfinder(map),marches=new MarchManager(pathfinder),training=new TrainingQueue(eco,army),battle=new BattleSimulator();
let selected:UnitCode='SWORDSMAN',view:View='city',castleLevel=12,research=43,heroXp=68;let log=['Bienvenido, comandante. El nuevo motor de Eternal Crown está activo.'];
const nav:[View,string,string][]=[['city','🏰','CIUDAD'],['map','🗺','MAPA'],['hero','♞','HÉROE'],['army','⚔','EJÉRCITO'],['research','⚗','INVESTIGACIÓN'],['alliance','♢','ALIANZA']];
const header=()=>{const r=eco.snapshot();return `<header><div class="logo">♛ <b>ETERNAL CROWN</b><small>ALPHA · ELYNDOR 0.3</small></div><div class="res"><span>🪵 ${Math.floor(r.WOOD)}</span><span>🌾 ${Math.floor(r.FOOD)}</span><span>⬡ ${Math.floor(r.STONE)}</span><span>● ${Math.floor(r.GOLD)}</span><span>◆ ${Math.floor(r.GEMS)}</span></div><div class="power">⚡ ${army.power().toLocaleString()}</div></header>`};
const bottom=()=>`<nav>${nav.map(([k,i,n])=>`<button data-view="${k}" class="${view===k?'on':''}">${i}<span>${n}</span></button>`).join('')}</nav>`;const shell=(body:string,side:string)=>`${header()}<main><section class="world">${body}</section><aside>${side}</aside></main>${bottom()}`;const chronicle=()=>`<div class="events"><b>CRÓNICA DEL REINO</b>${log.slice(-6).reverse().map(x=>`<p>› ${x}</p>`).join('')}</div>`;
function city(){return shell(`<div class="city-scene"><div class="sun"></div><div class="ridge r1"></div><div class="ridge r2"></div><div class="river-city"></div><div class="castle3d"><div class="castle-keep">♛</div><div class="tower3d a"></div><div class="tower3d b"></div><div class="wall3d"></div><b>CASTILLO · NIVEL ${castleLevel}</b></div><button class="city-building farm-b">🌾<b>Granja</b><small>Nivel 8</small></button><button class="city-building lumber-b">🪵<b>Aserradero</b><small>Nivel 7</small></button><button class="city-building barracks-b">⚔<b>Cuartel</b><small>Nivel 9</small></button><button class="city-building academy-b">⚗<b>Academia</b><small>Nivel 6</small></button><div class="city-label"><strong>ELYNDOR</strong><span>Capital del Reino del Norte</span></div></div>`,`<h2>Consejo Real</h2><p class="muted">Gobierna, produce y expande tu capital.</p><div class="card"><b>Producción por hora</b><p>🌾 Comida <strong>+1.280</strong></p><p>🪵 Madera <strong>+940</strong></p><p>⬡ Piedra <strong>+610</strong></p></div><button class="gold" id="upgrade-castle">MEJORAR CASTILLO · 2.400 🪵</button><button class="soft" id="collect">RECAUDAR PRODUCCIÓN</button>${chronicle()}`)}
function mapView(){const icon=(t:TerrainType)=>['·','♣','▲','≈','░','✦'][t];return shell(`<div class="title"><b>REINO DE ELYNDOR</b><span>Mapa táctico · sector 247,389</span></div><div class="map">${Array.from({length:map.size()},(_,i)=>`<button class="tile t${map.terrainAt(i)}">${icon(map.terrainAt(i))}${i===map.ref(4,5)?'<i>🏰</i>':i===map.ref(15,4)?'<i>🏯</i>':i===map.ref(13,8)?'<i>⛺</i>':i===map.ref(7,4)?'<i>🗿</i>':''}</button>`).join('')}<div class="route">${marches.active().length?marches.active().map(m=>`⚔ ${m.mission}: ${m.path.length} casillas`).join('<br>'):'Sin marchas activas'}</div></div>`,`<h2>Fortaleza Sombría</h2><div class="card"><b>🏯 Objetivo hostil</b><p>Poder <strong>31.400</strong></p><p>Ruta <strong>${pathfinder.find(map.ref(4,5),map.ref(15,4))?.path.length??0} casillas</strong></p></div><button class="red" id="attack">ATACAR FORTALEZA SOMBRÍA</button><button class="soft" id="scout">ENVIAR EXPLORADORES</button>${chronicle()}`)}
function armyView(){return shell(`<div class="army-scene"><div class="army-banner">⚔</div><h1>EJÉRCITO REAL</h1><p>${army.total()} soldados bajo tu mando</p><div class="formations"><div>🛡<b>Guardia Real</b><span>Primera línea</span></div><div>➶<b>Arqueros</b><span>Apoyo</span></div><div>♞<b>Caballería</b><span>Flanco</span></div></div></div>`,`<h2>Ejército Real</h2>${(Object.keys(UNITS)as UnitCode[]).map(c=>`<button class="unit ${selected===c?'sel':''}" data-unit="${c}"><i>${c==='SWORDSMAN'?'⚔':c==='ARCHER'?'➶':c==='KNIGHT'?'♞':'✦'}</i><span><b>${UNITS[c].name}</b><small>ATQ ${UNITS[c].attack} · DEF ${UNITS[c].defense}</small></span><strong>${army.count(c)}</strong></button>`).join('')}<button class="gold" id="train">ENTRENAR 5 ${UNITS[selected].name.toUpperCase()}</button>${chronicle()}`)}
function heroView(){return shell(`<div class="hero-scene"><div class="hero-moon"></div><div class="hero-silhouette">♞</div><div class="hero-name"><span>GUARDIÁN DE ELYNDOR</span><h1>ARTHUR</h1><p>«La corona perdura mientras quede un guerrero en pie.»</p></div></div>`,`<div class="hero-level"><span>NIVEL</span><b>12</b><small>${heroXp}% hacia nivel 13</small><div><i style="width:${heroXp}%"></i></div></div><div class="statgrid"><div>⚔<span>Ataque</span><b>248</b></div><div>🛡<span>Defensa</span><b>196</b></div><div>❤<span>Vida</span><b>3.420</b></div><div>✦<span>Crítico</span><b>18%</b></div></div><button class="gold" id="hero-train">ENTRENAR HÉROE · 500 ●</button>${chronicle()}`)}
function researchView(){return shell(`<div class="research-scene"><h1>ÁRBOL DE INVESTIGACIÓN</h1><div class="tech-tree">${[['⚔','Acero',100],['🛡','Murallas',100],['🌾','Agricultura',100],['🪵','Carpintería',100],['♞','Caballería',research],['✦','Magia',0],['♛','Dominio',0]].map((n,i)=>`<button class="tech n${i} ${Number(n[2])===100?'done':Number(n[2])>0?'active':''}"><i>${n[0]}</i><b>${n[1]}</b><small>${n[2]}%</small></button>`).join('')}</div></div>`,`<h2>Tácticas de caballería</h2><p class="muted">Aumenta ataque y velocidad.</p><div class="big-progress"><i style="width:${research}%"></i></div><button class="gold" id="research">INVESTIGAR +12%</button>${chronicle()}`)}
function allianceView(){return shell(`<div class="alliance-scene"><div class="crest">♛</div><h1>GUARDIANES DE ELYNDOR</h1><p>Honor · Lealtad · Gloria eterna</p><div class="alliance-kpis"><span><b>24</b>Miembros</span><span><b>1.8M</b>Poder</span><span><b>#37</b>Ranking</span></div></div>`,`<h2>Alianza</h2>${[['♛','Aldric'],['♞','Lyanna'],['⚔','Roderic'],['✦','Selene']].map((m,i)=>`<div class="member"><i>${m[0]}</i><span><b>${m[1]}</b><small>${i?'Oficial':'Líder'}</small></span></div>`).join('')}<button class="gold" id="aid">SOLICITAR AYUDA</button>${chronicle()}`)}
function render(){app.innerHTML=view==='city'?city():view==='map'?mapView():view==='hero'?heroView():view==='army'?armyView():view==='research'?researchView():allianceView();bind()}
function bind(){document.querySelectorAll<HTMLElement>('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view as View;render()});document.querySelectorAll<HTMLElement>('[data-unit]').forEach(b=>b.onclick=()=>{selected=b.dataset.unit as UnitCode;render()});document.querySelector('#train')?.addEventListener('click',()=>{try{const o=training.start(selected,5,Date.now());training.tick(o.finishAt);log.push(`Entrenamiento completado: 5 ${UNITS[selected].name}.`)}catch(e){log.push((e as Error).message)}render()});document.querySelector('#attack')?.addEventListener('click',()=>{try{const m=marches.dispatch('ATTACK',map.ref(4,5),map.ref(15,4),army.snapshot(),12);const result=battle.simulate({id:'elyndor',stacks:(Object.keys(UNITS)as UnitCode[]).map(c=>({...UNITS[c],unit:c,count:army.count(c)}))},{id:'shadow',stacks:[{unit:'ORC',count:430,attack:38,defense:31,health:95}]},m.id);log.push(`${result.winner==='ATTACKER'?'VICTORIA':'DERROTA'} en Fortaleza Sombría · ${result.rounds.length} rondas.`)}catch(e){log.push((e as Error).message)}render()});document.querySelector('#collect')?.addEventListener('click',()=>{eco.grant({FOOD:640,WOOD:470,STONE:305});log.push('Producción recaudada.');render()});document.querySelector('#upgrade-castle')?.addEventListener('click',()=>{if(eco.spend({WOOD:2400})){castleLevel++;log.push(`Castillo mejorado a nivel ${castleLevel}.`)}render()});document.querySelector('#hero-train')?.addEventListener('click',()=>{if(eco.spend({GOLD:500})){heroXp=Math.min(100,heroXp+9);log.push('Arthur ha entrenado.')}render()});document.querySelector('#research')?.addEventListener('click',()=>{research=Math.min(100,research+12);log.push(`Investigación: ${research}%.`);render()});document.querySelector('#scout')?.addEventListener('click',()=>{log.push('Exploradores enviados.');render()});document.querySelector('#aid')?.addEventListener('click',()=>{log.push('Petición de ayuda enviada.');render()})}
render();