import './guided-game.css';

type Phase=1|2|3|4|5|6|7;
type State={phase:Phase;step:number;resources:{wood:number;food:number;stone:number;gold:number};army:number;castle:number;territories:number;hero:number;research:number;morale:number;reputation:number;completed:number[];log:string[]};
const KEY='eternal-guided-v1';
const initial:State={phase:1,step:0,resources:{wood:12000,food:9000,stone:7000,gold:4500},army:120,castle:10,territories:1,hero:12,research:0,morale:82,reputation:50,completed:[],log:['Arthur recibe la Corona de Elyndor.']};
let state:State=load();
const app=document.querySelector<HTMLDivElement>('#app')!;
const phases=[
 ['El Despertar','Explora la amenaza y asegura Elyndor.',['Explorar la Fortaleza Sombría','Entrenar 100 soldados','Atacar la Fortaleza','Investigar Sabiduría']],
 ['Expansión del Reino','Haz crecer la economía y las defensas.',['Recaudar producción','Mejorar Granja','Mejorar Almacén','Mejorar Viviendas']],
 ['Mapa y Conquista','Expande Elyndor más allá de sus murallas.',['Explorar Bosque de Aelwyn','Conquistar Ruinas de Vaelor','Tomar Torre del Cuervo']],
 ['Legado de la Corona','Desarrolla a Arthur y la ciencia del reino.',['Entrenar a Arthur','Desbloquear Inspiración Real','Investigar Acero Templado','Completar árbol tecnológico']],
 ['El Arte de la Guerra','Domina formaciones, terreno y moral.',['Vencer con Línea','Vencer con Falange','Vencer con Cuña']],
 ['Crónicas de la Corona','Decide qué clase de reino gobernarás.',['Resolver al prisionero','Salvar la cosecha','Juzgar la Corona Dividida']],
 ['Diplomacia','Define aliados, socios y enemigos.',['Firmar tratado con Aelwyn','Comerciar con Solaria','Declarar guerra a Vaelor']]
] as const;
function load(){try{return {...initial,...JSON.parse(localStorage.getItem(KEY)||'null')}}catch{return structuredClone(initial)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function phaseData(){return phases[state.phase-1]}
function pct(){return Math.round((state.completed.length/7)*100)}
function push(msg:string){state.log.push(msg);if(state.log.length>8)state.log.shift()}
function finishStep(){const steps=phaseData()[2];state.step++;if(state.step>=steps.length){state.completed.push(state.phase);push(`Fase ${state.phase} completada.`);if(state.phase<7){state.phase=(state.phase+1) as Phase;state.step=0}else push('La campaña de Elyndor ha sido completada.')}}
function doAction(){const p=state.phase,s=state.step;
 if(p===1){if(s===0){push('Exploradores localizan la Fortaleza Sombría.')}if(s===1){if(state.resources.food<500) return;state.resources.food-=500;state.army+=100;push('100 soldados se unen al ejército.')}if(s===2){state.morale+=4;push('Victoria en la Fortaleza Sombría.')}if(s===3){state.research+=15;push('La Academia descubre Sabiduría I.')}}
 if(p===2){if(s===0){state.resources.wood+=1800;state.resources.food+=2200;state.resources.stone+=1200;push('Producción recaudada.')}if(s===1){state.resources.wood-=700;push('La Granja alcanza un nuevo nivel.')}if(s===2){state.resources.stone-=600;push('El Almacén ha sido ampliado.')}if(s===3){state.castle++;push('Nuevas viviendas aumentan la capacidad del reino.')}}
 if(p===3){if(s===0){push('Bosque de Aelwyn explorado.')}if(s===1){state.territories++;push('Ruinas de Vaelor conquistadas.')}if(s===2){state.territories++;push('Torre del Cuervo incorporada a Elyndor.')}}
 if(p===4){if(s===0){state.hero++;push(`Arthur alcanza nivel ${state.hero}.`)}if(s===1){state.morale+=5;push('Arthur desbloquea Inspiración Real.')}if(s===2){state.research+=25;push('Acero Templado investigado.')}if(s===3){state.research=100;push('Árbol tecnológico completado.')}}
 if(p===5){state.morale=Math.min(100,state.morale+3);push(`Victoria táctica ${['con Línea','con Falange','con Cuña'][s]}.`)}
 if(p===6){state.reputation+=s===1?-2:5;push(['El prisionero recibe clemencia.','La cosecha se salva mediante investigación.','El Consejo acepta el juicio de Arthur.'][s])}
 if(p===7){if(s===0){state.reputation+=8;push('Tratado firmado con Aelwyn.')}if(s===1){state.resources.gold+=900;push('Caravana comercial de Solaria recibida.')}if(s===2){state.morale+=6;push('Elyndor declara la guerra a Vaelor.')}}
 finishStep();save();render();}
function goPhase(p:Phase){if(p===state.phase||state.completed.includes(p)){state.phase=p;state.step=state.completed.includes(p)?phases[p-1][2].length:state.step;render()}}
function reset(){if(confirm('¿Reiniciar la campaña completa?')){state=structuredClone(initial);save();render()}}
function hero(){return `<div class="hero-card"><div class="portrait">♞</div><div><span>GUARDIÁN DE ELYNDOR</span><h2>Arthur</h2><p>Nivel ${state.hero} · Moral ${state.morale}% · Reputación ${state.reputation}</p></div></div>`}
function phaseNav(){return phases.map((p,i)=>{const n=i+1,done=state.completed.includes(n),locked=n>state.phase&&!done;return `<button class="phase-nav ${n===state.phase?'active':''} ${done?'done':''}" data-phase="${n}" ${locked?'disabled':''}><i>${done?'✓':n}</i><span><b>Fase ${n}</b><small>${p[0]}</small></span></button>`}).join('')}
function render(){const [title,desc,steps]=phaseData();const done=state.completed.includes(state.phase);const current=steps[Math.min(state.step,steps.length-1)];app.innerHTML=`<div class="game-shell"><header class="topbar"><div class="brand"><b>♛ ETERNAL CROWN</b><small>ELYNDOR · CAMPAÑA GUIADA 1.2</small></div><div class="resources"><span>🪵 ${state.resources.wood.toLocaleString()}</span><span>🌾 ${state.resources.food.toLocaleString()}</span><span>⬡ ${state.resources.stone.toLocaleString()}</span><span>● ${state.resources.gold.toLocaleString()}</span></div><div class="progress"><span>CAMPAÑA</span><b>${pct()}%</b><div><i style="width:${pct()}%"></i></div></div></header><aside class="sidebar"><div class="sidebar-title">CAMPAÑA</div>${phaseNav()}<button class="reset" id="reset">↻ Reiniciar partida</button></aside><main class="stage"><section class="world-art"><div class="sky"></div><div class="mountains"></div><div class="castle"><div class="keep">♛</div><div class="tower t1"></div><div class="tower t2"></div><div class="wall"></div></div><div class="banner"><small>FASE ${state.phase}</small><h1>${title}</h1><p>${desc}</p></div><div class="world-stats"><span><b>${state.army}</b> soldados</span><span><b>${state.territories}</b> territorios</span><span><b>${state.castle}</b> castillo</span><span><b>${state.research}%</b> ciencia</span></div></section><section class="mission-panel">${hero()}<div class="mission-head"><div><small>OBJETIVO ACTUAL</small><h3>${done?'Fase completada':current}</h3></div><strong>${Math.min(state.step,steps.length)}/${steps.length}</strong></div><div class="step-list">${steps.map((x,i)=>`<div class="step ${i<state.step||done?'done':i===state.step?'current':''}"><i>${i<state.step||done?'✓':i+1}</i><span>${x}</span></div>`).join('')}</div>${!done?`<button class="primary" id="action">${actionLabel(state.phase,state.step)}</button>`:`<div class="phase-complete">✓ FASE ${state.phase} COMPLETADA</div>`}<div class="hint"><b>¿Qué hago ahora?</b><p>${done?'Selecciona la siguiente fase desbloqueada en el menú de la izquierda.':'Completa el objetivo resaltado. Solo hay una acción principal disponible para evitar dudas.'}</p></div><div class="chronicle"><b>CRÓNICA</b>${state.log.slice().reverse().map(x=>`<p>› ${x}</p>`).join('')}</div></section></main></div>`;document.querySelector('#action')?.addEventListener('click',doAction);document.querySelector('#reset')?.addEventListener('click',reset);document.querySelectorAll<HTMLElement>('[data-phase]').forEach(b=>b.onclick=()=>goPhase(Number(b.dataset.phase) as Phase))}
function actionLabel(p:Phase,s:number){const labels=[['EXPLORAR','ENTRENAR 100 SOLDADOS','ATACAR FORTALEZA','INVESTIGAR'],['RECAUDAR','MEJORAR GRANJA','MEJORAR ALMACÉN','MEJORAR VIVIENDAS'],['EXPLORAR AELWYN','CONQUISTAR VAELOR','TOMAR TORRE'],['ENTRENAR ARTHUR','DESBLOQUEAR HABILIDAD','INVESTIGAR ACERO','COMPLETAR ÁRBOL'],['LUCHAR EN LÍNEA','LUCHAR EN FALANGE','LUCHAR EN CUÑA'],['ELEGIR CLEMENCIA','INVESTIGAR LA PLAGA','EMITIR JUICIO'],['FIRMAR TRATADO','COMERCIAR','DECLARAR GUERRA']];return labels[p-1][s]||'CONTINUAR'}
render();