import Phaser from 'phaser';
import './style.css';

type Building={id:string;code:string;name:string;level:number;productionPerHour:number;positionX:number;positionY:number};
type Construction={id:string;buildingCode:string;fromLevel:number;toLevel:number;startedAt:string;finishAt:string;remainingSeconds:number};
type KingdomState={kingdomId:string;kingdomName:string;kingdomLevel:number;resources:Record<string,number>;buildings:Building[];construction:Construction|null;serverTime:string};
type TutorialState={farmRewardClaimed:boolean;farm2RewardClaimed:boolean;sawmillRewardClaimed:boolean};

type BuildCfg={code:string;name:string;resource:string;baseProduction:number;seconds:number;cost:Record<string,number>};

const IS_DEMO=window.location.hostname.endsWith('github.io')||import.meta.env.VITE_DEMO_MODE==='true';
const API_BASE=(import.meta.env.VITE_API_BASE_URL??'http://localhost:8080').replace(/\/$/,'');
const DEMO_KEY='eternal-crown-demo-state-v2';
const TUTORIAL_KEY='eternal-crown-tutorial-v2';
const BUILD:Record<string,BuildCfg>={
 FARM:{code:'FARM',name:'Granja',resource:'FOOD',baseProduction:600,seconds:5,cost:{WOOD:100}},
 SAWMILL:{code:'SAWMILL',name:'Aserradero',resource:'WOOD',baseProduction:420,seconds:7,cost:{FOOD:180,STONE:80}},
 QUARRY:{code:'QUARRY',name:'Cantera',resource:'STONE',baseProduction:300,seconds:9,cost:{FOOD:220,WOOD:140}}
};

function building(code:string,name:string,x:number,y:number):Building{return{id:`${code.toLowerCase()}-demo`,code,name,level:0,productionPerHour:0,positionX:x,positionY:y}}
function createDemoState():KingdomState{return{kingdomId:'demo-kingdom',kingdomName:'Reino de Elyndor',kingdomLevel:1,resources:{FOOD:500,WOOD:500,STONE:500,GOLD:500,GEMS:100},buildings:[{id:'castle-demo',code:'CASTLE',name:'Castillo',level:1,productionPerHour:0,positionX:0,positionY:0},building('FARM','Granja',1,1),building('SAWMILL','Aserradero',2,1),building('QUARRY','Cantera',3,1)],construction:null,serverTime:new Date().toISOString()}}
function saveDemoState(s:KingdomState){localStorage.setItem(DEMO_KEY,JSON.stringify(s))}
function tutorialDefault():TutorialState{return{farmRewardClaimed:false,farm2RewardClaimed:false,sawmillRewardClaimed:false}}
function loadTutorial():TutorialState{try{return{...tutorialDefault(),...JSON.parse(localStorage.getItem(TUTORIAL_KEY)??'{}')}}catch{return tutorialDefault()}}
function saveTutorial(s:TutorialState){localStorage.setItem(TUTORIAL_KEY,JSON.stringify(s))}
function prodFor(code:string,level:number){const c=BUILD[code];return c?Math.round(c.baseProduction*Math.pow(1.45,Math.max(0,level-1))):0}
function ensureDemoBuildings(s:KingdomState){for(const [code,cfg,x,y] of [['FARM',BUILD.FARM,1,1],['SAWMILL',BUILD.SAWMILL,2,1],['QUARRY',BUILD.QUARRY,3,1]] as const){if(!s.buildings.find(b=>b.code===code))s.buildings.push(building(code,cfg.name,x,y))}}
function loadDemoState():KingdomState{
 const raw=localStorage.getItem(DEMO_KEY);const s=raw?JSON.parse(raw) as KingdomState:createDemoState();ensureDemoBuildings(s);const now=Date.now();
 if(s.construction){const finish=new Date(s.construction.finishAt).getTime();if(now>=finish){const b=s.buildings.find(x=>x.code===s.construction?.buildingCode);if(b){b.level=s.construction.toLevel;b.productionPerHour=prodFor(b.code,b.level)}s.construction=null}else s.construction.remainingSeconds=Math.ceil((finish-now)/1000)}
 const last=new Date(s.serverTime).getTime();if(now>last){const hours=(now-last)/3600000;for(const b of s.buildings){const cfg=BUILD[b.code];if(cfg&&b.level>0)s.resources[cfg.resource]=(s.resources[cfg.resource]??0)+b.productionPerHour*hours}}
 s.serverTime=new Date(now).toISOString();saveDemoState(s);return s;
}
async function loadKingdom(){if(IS_DEMO)return loadDemoState();const r=await fetch(`${API_BASE}/api/kingdom`);if(!r.ok)throw new Error('No se pudo cargar el reino');return r.json() as Promise<KingdomState>}
function costFor(code:string,targetLevel:number){const cfg=BUILD[code];const factor=Math.pow(1.65,Math.max(0,targetLevel-1));const out:Record<string,number>={};for(const[k,v]of Object.entries(cfg.cost))out[k]=Math.round(v*factor);return out}
function hasCost(s:KingdomState,cost:Record<string,number>){return Object.entries(cost).every(([k,v])=>(s.resources[k]??0)>=v)}
function costText(cost:Record<string,number>){const icon:Record<string,string>={FOOD:'🌾',WOOD:'🪵',STONE:'🪨'};return Object.entries(cost).map(([k,v])=>`${icon[k]??''}${v}`).join('  ')}
async function upgradeBuilding(code:string){
 if(IS_DEMO){const s=loadDemoState(),b=s.buildings.find(x=>x.code===code);if(!b||s.construction)return s;const target=b.level+1,cost=costFor(code,target);if(!hasCost(s,cost))throw new Error('No tienes recursos suficientes');for(const[k,v]of Object.entries(cost))s.resources[k]-=v;const seconds=Math.min(40,BUILD[code].seconds+Math.max(0,target-1)*5),start=new Date(),finish=new Date(start.getTime()+seconds*1000);s.construction={id:crypto.randomUUID(),buildingCode:code,fromLevel:b.level,toLevel:target,startedAt:start.toISOString(),finishAt:finish.toISOString(),remainingSeconds:seconds};saveDemoState(s);return s}
 if(code!=='FARM')throw new Error('Disponible por ahora en la demo web');const r=await fetch(`${API_BASE}/api/kingdom/farm/upgrade`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requestId:crypto.randomUUID()})});if(!r.ok)throw new Error('No se pudo mejorar la granja');return r.json() as Promise<KingdomState>;
}

class KingdomScene extends Phaser.Scene{
 private state?:KingdomState;private status?:Phaser.GameObjects.Text;private selected='FARM';
 constructor(){super('KingdomScene')}
 create(){this.cameras.main.setBackgroundColor('#5d793e');this.scale.on('resize',()=>this.renderScene());this.status=this.add.text(16,16,'Cargando...',{fontFamily:'system-ui',fontSize:'15px',color:'#fff',backgroundColor:'#000a',padding:{x:10,y:7}}).setDepth(80);void this.refresh();this.time.addEvent({delay:1000,loop:true,callback:()=>void this.refresh(false)})}
 private async refresh(showError=true){try{this.state=await loadKingdom();this.status?.setText('');this.updateHud();this.renderScene()}catch(e){if(showError)this.flash(e instanceof Error?e.message:'Error')}}
 private updateHud(){if(!this.state)return;for(const [key,id] of Object.entries({FOOD:'res-food',WOOD:'res-wood',STONE:'res-stone',GOLD:'res-gold',GEMS:'res-gems'})){const el=document.getElementById(id);if(el)el.textContent=Math.floor(this.state.resources[key]??0).toLocaleString('es-ES')}}
 private renderScene(){if(!this.state)return;const{width:w,height:h}=this.scale,t=loadTutorial(),construction=this.state.construction;this.children.list.filter(c=>c!==this.status).forEach(c=>c.destroy());const farm=this.getB('FARM'),sawmill=this.getB('SAWMILL'),quarry=this.getB('QUARRY');
 const g=this.add.graphics();g.fillStyle(0x6f914d).fillRect(0,0,w,h);g.fillStyle(0x668846).fillEllipse(w*.5,h*.53,w*.95,h*.94);g.lineStyle(2,0x789c55,.3);for(let y=32;y<h;y+=48)g.lineBetween(0,y,w,y+70);
 this.drawRiver(g,w,h);this.drawPaths(g,w,h);[[.07,.2],[.11,.3],[.08,.42],[.31,.18],[.36,.25],[.87,.18],[.91,.3],[.9,.46],[.83,.68],[.32,.79],[.38,.84],[.08,.78]].forEach(([x,y],i)=>this.drawTree(w*x,h*y,16+(i%3)*3));
 this.drawCastle(w*.49,h*.40,Math.max(.68,Math.min(1.05,w/1180)));
 const unlockedSawmill=farm.level>=2||t.farm2RewardClaimed;const unlockedQuarry=sawmill.level>=1||t.sawmillRewardClaimed;
 this.drawResourceBuilding(w*.68,h*.59,'FARM',farm.level,construction?.buildingCode==='FARM',true);
 this.drawResourceBuilding(w*.34,h*.56,'SAWMILL',sawmill.level,construction?.buildingCode==='SAWMILL',unlockedSawmill);
 this.drawResourceBuilding(w*.80,h*.34,'QUARRY',quarry.level,construction?.buildingCode==='QUARRY',unlockedQuarry);
 this.label(w*.49,h*.57,'CASTILLO','Nivel 1');this.buildingLabel(w*.68,h*.70,farm);this.buildingLabel(w*.34,h*.68,sawmill,unlockedSawmill);this.buildingLabel(w*.80,h*.45,quarry,unlockedQuarry);
 this.addBuildingHit(w*.68,h*.59,'FARM',true);this.addBuildingHit(w*.34,h*.56,'SAWMILL',unlockedSawmill);this.addBuildingHit(w*.80,h*.34,'QUARRY',unlockedQuarry);
 if(IS_DEMO)this.add.text(w-10,10,'DEMO',{fontFamily:'system-ui',fontSize:'10px',color:'#ead59a',backgroundColor:'#20251dcc',padding:{x:7,y:4}}).setOrigin(1,0).setDepth(60);
 this.drawMission(w,h,farm,sawmill,quarry,t,construction);this.drawAction(w,h,farm,sawmill,quarry,t,construction,unlockedSawmill,unlockedQuarry);
 }
 private getB(code:string){return this.state!.buildings.find(b=>b.code===code)!}
 private drawRiver(g:Phaser.GameObjects.Graphics,w:number,h:number){g.fillStyle(0x3c7782,.9);g.beginPath();g.moveTo(w*.03,h);g.lineTo(w*.16,h*.72);g.lineTo(w*.12,h*.48);g.lineTo(w*.2,h*.25);g.lineTo(w*.17,0);g.lineTo(w*.28,0);g.lineTo(w*.30,h*.26);g.lineTo(w*.23,h*.5);g.lineTo(w*.28,h*.73);g.lineTo(w*.18,h);g.closePath();g.fillPath()}
 private drawPaths(g:Phaser.GameObjects.Graphics,w:number,h:number){g.lineStyle(Math.max(18,w*.021),0xb89b69,.84);g.beginPath();g.moveTo(w*.49,h*.49);g.lineTo(w*.40,h*.58);g.lineTo(w*.34,h*.60);g.moveTo(w*.49,h*.49);g.lineTo(w*.60,h*.58);g.lineTo(w*.72,h*.66);g.moveTo(w*.55,h*.43);g.lineTo(w*.70,h*.36);g.lineTo(w*.80,h*.36);g.strokePath()}
 private drawMission(w:number,h:number,farm:Building,sawmill:Building,quarry:Building,t:TutorialState,c:Construction|null){const m=this.mission(farm,sawmill,quarry,t,c),g=this.add.graphics(),pw=Math.min(365,w*.48),ph=102,px=14,py=h-ph-14;g.fillStyle(0x171a15,.94).fillRoundedRect(px,py,pw,ph,10);g.lineStyle(1,0xb39250,.9).strokeRoundedRect(px,py,pw,ph,10);this.add.text(px+14,py+10,m.header,{fontFamily:'system-ui',fontStyle:'bold',fontSize:'11px',color:m.done?'#8edb86':'#d9b96b'});this.add.text(px+14,py+30,m.title,{fontFamily:'Georgia',fontStyle:'bold',fontSize:'18px',color:'#fff3ce'});this.add.text(px+14,py+57,m.detail,{fontFamily:'system-ui',fontSize:'11px',color:'#b8bdad'});if(m.reward)this.add.text(px+14,py+78,m.reward,{fontFamily:'system-ui',fontStyle:'bold',fontSize:'11px',color:'#f2d382'})}
 private mission(f:Building,s:Building,q:Building,t:TutorialState,c:Construction|null){if(c)return{header:'CONSTRUCTOR OCUPADO',title:`Construyendo ${BUILD[c.buildingCode]?.name??'edificio'}`,detail:`Termina en ${this.formatTime(c.remainingSeconds)}. La producción continúa.`,reward:'',done:false};if(f.level===0)return{header:'MISIÓN 1',title:'Construye una granja',detail:'La comida alimentará población y ejército.',reward:'Recompensa: +75 madera',done:false};if(!t.farmRewardClaimed)return{header:'MISIÓN COMPLETADA ✓',title:'La granja ya produce',detail:'Has creado tu primera fuente de recursos.',reward:'Reclama +75 madera',done:true};if(f.level<2)return{header:'MISIÓN 2',title:'Mejora la granja a nivel 2',detail:'Más producción desbloqueará nuevos edificios.',reward:'Recompensa: +100 piedra',done:false};if(!t.farm2RewardClaimed)return{header:'MISIÓN COMPLETADA ✓',title:'Producción reforzada',detail:'El Aserradero ya está desbloqueado.',reward:'Reclama +100 piedra',done:true};if(s.level===0)return{header:'MISIÓN 3',title:'Construye el Aserradero',detail:'Producirá madera incluso cuando no estés jugando.',reward:'Recompensa: +120 comida',done:false};if(!t.sawmillRewardClaimed)return{header:'MISIÓN COMPLETADA ✓',title:'La madera ya fluye',detail:'Has desbloqueado la Cantera.',reward:'Reclama +120 comida',done:true};if(q.level===0)return{header:'MISIÓN 4',title:'Construye la Cantera',detail:'La piedra permitirá murallas y edificios militares.',reward:'Nuevo objetivo: preparar el cuartel',done:false};return{header:'ECONOMÍA BÁSICA COMPLETA ✓',title:'Tu reino ya se sostiene',detail:'Comida, madera y piedra se producen con el tiempo.',reward:'Siguiente fase: ejército y combate',done:true}}
 private drawAction(w:number,h:number,f:Building,s:Building,q:Building,t:TutorialState,c:Construction|null,us:boolean,uq:boolean){const bx=Math.min(w-116,w*.70),by=Math.min(h-62,h*.84);if(c){this.actionButton(bx,by,'CONSTRUCCIÓN EN CURSO',this.formatTime(c.remainingSeconds),0x383426,false);return}let reward:{key:keyof TutorialState;resource:string;amount:number}|null=null;if(f.level>0&&!t.farmRewardClaimed)reward={key:'farmRewardClaimed',resource:'WOOD',amount:75};else if(f.level>=2&&!t.farm2RewardClaimed)reward={key:'farm2RewardClaimed',resource:'STONE',amount:100};else if(s.level>0&&!t.sawmillRewardClaimed)reward={key:'sawmillRewardClaimed',resource:'FOOD',amount:120};if(reward&&IS_DEMO){const b=this.actionButton(bx,by,'RECLAMAR RECOMPENSA',`+${reward.amount} ${this.resourceName(reward.resource)}`,0x3e7338);b.on('pointerdown',()=>this.claim(reward!));this.tweens.add({targets:b,scaleX:1.04,scaleY:1.04,duration:650,yoyo:true,repeat:-1});return}
 const map:Record<string,{b:Building;unlocked:boolean}>={FARM:{b:f,unlocked:true},SAWMILL:{b:s,unlocked:us},QUARRY:{b:q,unlocked:uq}};const x=map[this.selected]??map.FARM;if(!x.unlocked){this.actionButton(bx,by,'EDIFICIO BLOQUEADO','Completa la misión anterior',0x4b4538,false);return}const target=x.b.level+1,cost=costFor(x.b.code,target),cfg=BUILD[x.b.code];const btn=this.actionButton(bx,by,x.b.level===0?`CONSTRUIR ${cfg.name.toUpperCase()}`:`MEJORAR ${cfg.name.toUpperCase()}`,costText(cost),0x80582c);btn.on('pointerdown',()=>void this.onUpgrade(x.b.code))}
 private claim(r:{key:keyof TutorialState;resource:string;amount:number}){const t=loadTutorial();if(t[r.key])return;const s=loadDemoState();s.resources[r.resource]=(s.resources[r.resource]??0)+r.amount;t[r.key]=true;saveDemoState(s);saveTutorial(t);this.state=s;this.updateHud();this.flash(`+${r.amount} ${this.resourceName(r.resource)}`);this.renderScene()}
 private resourceName(r:string){return({WOOD:'madera',STONE:'piedra',FOOD:'comida'} as Record<string,string>)[r]??r.toLowerCase()}
 private addBuildingHit(x:number,y:number,code:string,enabled:boolean){const hit=this.add.zone(x,y,145,115).setDepth(y+20);if(enabled)hit.setInteractive({useHandCursor:true}).on('pointerdown',()=>{this.selected=code;this.renderScene()})}
 private drawResourceBuilding(x:number,y:number,code:string,level:number,busy:boolean,unlocked:boolean){const g=this.add.graphics().setDepth(y);if(!unlocked){g.fillStyle(0x24271f,.45).fillRoundedRect(x-55,y-36,110,72,8);this.add.text(x,y,'🔒',{fontSize:'28px'}).setOrigin(.5).setDepth(y+3);return}g.fillStyle(0x413622,.22).fillEllipse(x,y+36,145,40);if(level===0&&!busy){g.lineStyle(3,0xd9bf78,.8).strokeRoundedRect(x-55,y-35,110,70,8);g.fillStyle(0xe7d078,.12).fillRoundedRect(x-55,y-35,110,70,8);this.add.text(x,y,'+', {fontFamily:'Georgia',fontSize:'38px',color:'#f4d981'}).setOrigin(.5).setDepth(y+2);return}if(code==='FARM'){g.fillStyle(0xd7c39b).fillRect(x-44,y-18,88,55);g.fillStyle(0x744333).fillTriangle(x-55,y-18,x,y-60,x+55,y-18);for(let i=0;i<4;i++){g.lineStyle(3,0xc8a34f,.8).lineBetween(x-68+i*30,y+48,x-50+i*30,y+66)}}else if(code==='SAWMILL'){g.fillStyle(0x9d7248).fillRect(x-48,y-22,96,60);g.fillStyle(0x5f3d29).fillTriangle(x-58,y-22,x,y-58,x+58,y-22);g.fillStyle(0x6e472c).fillRect(x-62,y+38,124,10);g.lineStyle(6,0x755139).lineBetween(x-70,y+54,x+72,y+54);g.lineStyle(3,0xd4b078).strokeCircle(x+38,y+13,19)}else{g.fillStyle(0x6d706b).fillTriangle(x-62,y+35,x-12,y-48,x+30,y+35);g.fillStyle(0x555953).fillTriangle(x-5,y+35,x+50,y-35,x+72,y+35);g.fillStyle(0x252722).fillEllipse(x+8,y+13,34,44);g.fillStyle(0xa18b5b).fillRect(x-60,y+40,120,10)}if(busy)this.add.text(x,y-76,'⚒',{fontSize:'25px'}).setOrigin(.5).setDepth(y+4)}
 private buildingLabel(x:number,y:number,b:Building,unlocked=true){const cfg=BUILD[b.code];const sub=!unlocked?'Bloqueado':b.level===0?'Toca para construir':`Nivel ${b.level} · +${Math.floor(b.productionPerHour)}/h`;this.label(x,y,b.name.toUpperCase(),sub)}
 private drawTree(x:number,y:number,s:number){const g=this.add.graphics();g.fillStyle(0x49331f).fillRect(x-s*.12,y,s*.24,s*.7);g.fillStyle(0x294c2c).fillTriangle(x,y-s*.95,x-s*.58,y-s*.08,x+s*.58,y-s*.08);g.fillStyle(0x355e34).fillTriangle(x,y-s*.65,x-s*.72,y+s*.18,x+s*.72,y+s*.18);g.setDepth(y)}
 private drawCastle(x:number,y:number,s:number){const g=this.add.graphics();g.fillStyle(0x39352f,.25).fillEllipse(x,y+70*s,210*s,55*s);g.fillStyle(0xb7aa8a).fillRect(x-78*s,y-28*s,156*s,100*s);g.fillStyle(0x8d826d).fillRect(x-100*s,y-60*s,45*s,132*s).fillRect(x+55*s,y-60*s,45*s,132*s).fillRect(x-30*s,y-86*s,60*s,158*s);g.fillStyle(0x5e4a37).fillTriangle(x-105*s,y-60*s,x-77*s,y-103*s,x-50*s,y-60*s).fillTriangle(x+50*s,y-60*s,x+77*s,y-103*s,x+105*s,y-60*s).fillTriangle(x-36*s,y-86*s,x,y-132*s,x+36*s,y-86*s);g.fillStyle(0x33281f).fillRoundedRect(x-16*s,y+25*s,32*s,47*s,5*s);g.fillStyle(0xe0b650).fillRect(x-4*s,y-125*s,5*s,36*s);g.fillStyle(0x9e3f31).fillTriangle(x+1*s,y-125*s,x+35*s,y-115*s,x+1*s,y-105*s);g.setDepth(y)}
 private label(x:number,y:number,title:string,sub:string){return this.add.text(x,y,`${title}\n${sub}`,{align:'center',fontFamily:'system-ui',fontStyle:'bold',fontSize:'10px',color:'#fff4cf',stroke:'#182014',strokeThickness:4,lineSpacing:2}).setOrigin(.5,0).setDepth(y+30)}
 private actionButton(x:number,y:number,title:string,sub:string,color=0x80582c,interactive=true){const c=this.add.container(x,y).setDepth(70).setSize(235,60);if(interactive)c.setInteractive({useHandCursor:true});const bg=this.add.rectangle(0,0,235,60,color,.98).setStrokeStyle(2,0xd1a75c);const a=this.add.text(0,-9,title,{fontFamily:'system-ui',fontStyle:'bold',fontSize:'13px',color:'#fff4d0'}).setOrigin(.5);const b=this.add.text(0,13,sub,{fontFamily:'system-ui',fontSize:'10px',color:'#e0c58d'}).setOrigin(.5);c.add([bg,a,b]);return c}
 private async onUpgrade(code:string){try{this.state=await upgradeBuilding(code);this.updateHud();this.renderScene()}catch(e){this.flash(e instanceof Error?e.message:'No se pudo iniciar')}}
 private flash(msg:string){this.status?.setText(msg).setBackgroundColor('#31522f');this.time.delayedCall(1800,()=>this.status?.setText('').setBackgroundColor('#000a'))}
 private formatTime(sec:number){const s=Math.max(0,sec),m=Math.floor(s/60);return`${String(m).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
}

new Phaser.Game({type:Phaser.AUTO,parent:'game',width:1280,height:720,backgroundColor:'#607f45',scale:{mode:Phaser.Scale.RESIZE,autoCenter:Phaser.Scale.CENTER_BOTH},scene:[KingdomScene]});
