import './reference-ui.css';

type Screen='city'|'map'|'hero'|'army'|'research'|'alliance'|'campaign'|'battle'|'victory';
const app=document.querySelector<HTMLDivElement>('#app')!;
const state={screen:'city' as Screen,wood:12500,food:8700,stone:4200,gold:3500,gems:210,power:24580,level:12,shield:'2h 34m'};
const icons:Record<string,string>={city:'♜',map:'🗺',hero:'♞',army:'⚔',research:'⚗',alliance:'♢',campaign:'★'};
const nav=[['city','CIUDAD'],['map','MAPA'],['hero','HÉROE'],['army','EJÉRCITO'],['research','INVESTIGACIÓN'],['alliance','ALIANZA'],['campaign','CAMPAÑA']] as const;
const res=()=>`<div class="resources"><span>🪵 <b>${state.wood.toLocaleString()}</b></span><span>🌾 <b>${state.food.toLocaleString()}</b></span><span>⬡ <b>${state.stone.toLocaleString()}</b></span><span>● <b>${state.gold.toLocaleString()}</b></span><span>◆ <b>${state.gems}</b></span></div>`;
const top=(title:string,sub='')=>`<header><div class="brand"><i>♛</i><div><b>ETERNAL CROWN</b><small>${sub||title}</small></div></div>${res()}<div class="power">⚡ <b>${state.power.toLocaleString()}</b></div><div class="avatar">12</div></header>`;
const bottom=()=>`<nav>${nav.map(([k,n])=>`<button data-screen="${k}" class="${state.screen===k?'on':''}"><i>${icons[k]}</i><span>${n}</span></button>`).join('')}</nav>`;
const shell=(body:string,title:string)=>`${top(title)}<main>${body}</main>${bottom()}`;
const castle=`<div class="castle"><div class="tower t1"></div><div class="tower t2"></div><div class="keep"><div class="roof"></div><div class="gate"></div></div><div class="wall"></div><div class="flag">◆</div></div>`;
function city(){return shell(`<section class="city scene"><div class="mountains"></div><div class="river"></div>${castle}<div class="building farm"><b>Granja</b><small>Nivel 8</small></div><div class="building lumber"><b>Aserradero</b><small>Nivel 7</small></div><div class="building quarry"><b>Cantera</b><small>Nivel 6</small></div><div class="building barracks"><b>Cuartel</b><small>Nivel 9</small></div><div class="bubble quest">!</div><div class="bubble shield">🛡<small>${state.shield}</small></div><aside class="mission"><b>MISIONES</b><p>Mejora el Castillo al nivel 13</p><div><i style="width:68%"></i></div><small>8 / 12</small></aside><button class="round settings">⚙</button><button class="round mail">✉</button></section>`,'Ciudad');}
function map(){return shell(`<section class="map scene"><div class="sea"></div><div class="land"></div><div class="fog"></div>${[['Tu ciudad','🏰','28,42'],['Fortaleza sombría','🏯','63,24'],['Aldea abandonada','🏚','52,57'],['Campamento orco','⛺','77,62'],['Ruinas antiguas','🗿','33,72']].map(([n,i,p])=>{const [x,y]=p.split(',');return `<button class="poi" style="left:${x}%;top:${y}%"><i>${i}</i><b>${n}</b></button>`}).join('')}<aside class="coords">X: 247 &nbsp; Y: 389</aside><div class="zoom"><button>＋</button><button>−</button></div><div class="mini"></div></section>`,'Mapa del Reino','Elyndor • Región Norte');}
function hero(){return shell(`<section class="hero scene"><div class="hero-art"><div class="moon"></div><div class="warrior">♞</div><h1>ARTHUR</h1><p>El Guardián de Elyndor</p></div><aside class="hero-panel"><div class="lvl">NIVEL <b>12</b><span>2,840 / 4,200 XP</span></div><h3>ESTADÍSTICAS</h3>${[['⚔','Ataque','248'],['🛡','Defensa','196'],['❤','Vida','3,420'],['✦','Crítico','18%']].map(x=>`<div class="stat"><i>${x[0]}</i><span>${x[1]}</span><b>${x[2]}</b></div>`).join('')}<h3>EQUIPAMIENTO</h3><div class="gear">${['⚔','⛑','♜','🛡','◈','◉'].map((x,i)=>`<button class="slot q${i%3}">${x}<small>+${i+4}</small></button>`).join('')}</div><button class="goldbtn">MEJORAR HÉROE</button></aside></section>`,'Héroe');}
function army(){return shell(`<section class="army scene"><div class="army-art"><div class="soldiers">⚔ ♞ ⚔</div><h1>EJÉRCITO REAL</h1></div><aside class="army-panel"><div class="cap"><b>CAPACIDAD</b><span>1,280 / 1,500</span><div><i style="width:85%"></i></div></div>${[['⚔','Espadachines','520','8'],['➶','Arqueros','380','7'],['♞','Caballería','240','6'],['✹','Magos','140','5']].map(x=>`<div class="troop"><i>${x[0]}</i><div><b>${x[1]}</b><small>Nivel ${x[3]}</small></div><strong>${x[2]}</strong><button>＋</button></div>`).join('')}<button class="goldbtn">ENTRENAR TROPAS</button></aside></section>`,'Ejército');}
function research(){return shell(`<section class="research scene"><h1>ÁRBOL DE INVESTIGACIÓN</h1><div class="tree">${[['⚔','Acero templado'],['🛡','Murallas reforzadas'],['🌾','Agricultura II'],['🪵','Carpintería'],['♞','Tácticas de caballería'],['✦','Magia ancestral'],['♛','Dominio real']].map((x,i)=>`<button class="node n${i} ${i<4?'done':''}"><i>${x[0]}</i><b>${x[1]}</b><small>${i<4?'Completado':'Bloqueado'}</small></button>`).join('')}</div><aside class="research-info"><b>INVESTIGANDO</b><h2>Tácticas de caballería</h2><p>Aumenta el ataque de caballería un 12%.</p><div class="timer">02:14:37</div><div class="progress"><i style="width:43%"></i></div><button class="goldbtn">ACELERAR · 35 ◆</button></aside></section>`,'Investigación');}
function alliance(){return shell(`<section class="alliance scene"><div class="alliance-art"><div class="crest">♛</div><h1>GUARDIANES DE ELYNDOR</h1><p>«Honor, lealtad y gloria eterna.»</p><div class="alliance-stats"><span><b>24</b>Miembros</span><span><b>1.8M</b>Poder</span><span><b>#37</b>Ranking</span></div></div><aside class="alliance-panel"><h3>MIEMBROS DESTACADOS</h3>${[['♛','Aldric','87,420'],['♞','Lyanna','75,180'],['⚔','Roderic','68,930'],['✦','Selene','61,500']].map((x,i)=>`<div class="member"><i>${x[0]}</i><div><b>${x[1]}</b><small>${i?'Oficial':'Líder'}</small></div><strong>${x[2]}</strong></div>`).join('')}<button class="goldbtn">CHAT DE ALIANZA</button></aside></section>`,'Alianza');}
function campaign(){return shell(`<section class="campaign scene"><h1>CAMPAÑA</h1><p>Capítulo III · Las Tierras Marchitas</p><div class="path"></div>${[1,2,3,4,5,6,7].map((n,i)=>`<button class="stage s${n} ${n<4?'won':n===4?'current':''}" data-battle="1"><i>${n<4?'★':n===4?'⚔':'🔒'}</i><b>${n}</b></button>`).join('')}<aside class="campaign-card"><b>ETAPA 3-4</b><h2>El Paso de Ceniza</h2><p>Poder recomendado: <strong>22,000</strong></p><div>Recompensas &nbsp; ● 1,200 &nbsp; 🪵 2,400</div><button class="goldbtn" data-battle="1">COMBATIR</button></aside></section>`,'Campaña');}
function battle(){return `${top('Batalla','El Paso de Ceniza')}<main><section class="battle scene"><div class="battlefield"><div class="enemy"><div class="hp"><i style="width:72%"></i></div><b>LEGIÓN SOMBRÍA</b><div class="enemy-units">♞ ⚔ ♞<br>⚔ ♛ ⚔</div></div><div class="vs">VS</div><div class="ally"><div class="ally-units">⚔ ♞ ⚔<br>➶ ♛ ➶</div><b>EJÉRCITO DE ELYNDOR</b><div class="hp"><i style="width:88%"></i></div></div></div><aside class="battle-controls"><button class="speed">×2</button><button class="skill">🔥<small>Golpe real</small></button><button class="skill">🛡<small>Muralla</small></button><button class="skill">⚡<small>Carga</small></button><button class="goldbtn" id="win">RESOLVER BATALLA</button></aside></section></main>`;}
function victory(){return `<div class="victory scene"><div class="rays"></div><div class="victory-card"><div class="crown">♛</div><h1>¡VICTORIA!</h1><p>El Paso de Ceniza ha sido conquistado</p><div class="stars">★ ★ ★</div><h3>RECOMPENSAS</h3><div class="rewards"><span>●<b>1,200</b></span><span>🪵<b>2,400</b></span><span>◆<b>15</b></span><span>✦<b>850 XP</b></span></div><button class="goldbtn" id="continue">CONTINUAR</button></div></div>`;}
function render(){const f={city,map,hero,army,research,alliance,campaign,battle,victory}[state.screen];app.innerHTML=f();bind();}
function bind(){document.querySelectorAll<HTMLElement>('[data-screen]').forEach(b=>b.onclick=()=>{state.screen=b.dataset.screen as Screen;render()});document.querySelectorAll<HTMLElement>('[data-battle]').forEach(b=>b.onclick=()=>{state.screen='battle';render()});document.querySelector('#win')?.addEventListener('click',()=>{state.screen='victory';render()});document.querySelector('#continue')?.addEventListener('click',()=>{state.screen='campaign';render()});}
render();