name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    name: Backend Java
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Java 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'
      - name: Compilar y probar backend
        run: mvn -B test

  frontend:
    name: Frontend UI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Node 22
        uses: actions/setup-node@v5
        with:
          node-version: '22'
      - name: Instalar dependencias
        run: npm install
      - name: Compilar frontend
        run: npm run build
